# Introducción a Python: nivel intermedio

Python es un lenguaje muy extendido, con una rica comunidad que abarca muchos aspectos, muy fácil de aprender y programar con él, y que nos permite realizar un montón de tareas diferentes. Pero, no solo de pan vive. Python tiene muchas _librerías_ o _módulos_ que nos facilitan muchas tareas, que están respaldados por un gran número de personas detrás y que en muchos casos, realizan tareas específicas de una manera mucho más eficiente que haciéndolo puramente en Python.

Este es el caso de librerías como ___NumPy___, ___Pandas___, ___scikit-learn___, ___Django___ y muchísimas más. 

Además de esto, aunque Python sea un lenguaje puramente imperativo, nos permite simular lo que se conoce como programación funcional, que viene directamente del _Lambda Calculus_, gracias al uso de las funciones ___lambda___.

A continuación, veremos una introducción a _NumPy_ que nos sirve como puerta de entrada a un montón de módulos más, y la programación funcional con las funciones _lambda_.

## NumPy

NumPy es el paquete central que usaremos para tareas como ciencia de datos, o muchos cálculos matemáticos que requieren el uso de estructuras algebraicas como los vectores y matrices. Este paquete tiene la ventaja de que podemos trabajar cómodamente con la sintaxis de Python, creando estructuras $n$-dimensionales de forma sencilla y realizar complejas funciones sobre estas estructuras en una sola línea de código muy eficiente. 

Esta eficiencia se debe a que NumPy utiliza código C para realizar estos cálculos, que es mucho más rápido que la misma implementación en Python.

Además de esto, otras de las grandes ventajas de NumPy es la documentación oficial que tiene, que es una de las más completas y bien documentadas que hay, ya que cubren muy bien todos los aspectos de las distintas funciones que tiene, además de incorporar una gran cantidad de ejemplos.

### Instalación

Para instalar NumPy tenemos que ejecutar la siguiente línea en nuestro terminal:
```
[braulio@braulio-PC ~]$ sudo pip install numpy
```
Con esto, gracias a pip, descargaremos e instalaremos NumPy. Así que, una vez instalados... a trabajar!!

### Primeros pasos con NumPy

Para empezar a trabajar con NumPy, lo primero es importar el paquete en nuestro script.

In [1]:
import numpy

Con esta línea, ya tendremos en nuestro pequeño script el paquete listo para ser usado. Para acceder a los módulos tendremos que hacer `numpy.nombre_de_la_función`. Esto no es que este mal, pero por así decirlo, el estandar es importar NumPy como se ve a continuación:

In [2]:
import numpy as np

De esta forma, vuestro código pasa a ser más legible, el resto de gente y mas cómodo y rápido de escribir. Además de que por convenio, debes importar NumPy como `np`.

### Arrays de NumPy

Numpy puede trabajar con arrays de $n$ dimensiones, pero los más comunes son los arrays de una, dos o tres dimensiones (1D, 2D, 3D). Además de esto, podemos establecer el tipo de los elementos del array a la hora de crearlo. Esto es muy importante, ya que si el array del tipo está determinado antes de ejecutar el script, Python no tiene que pararse a inferir el tipo de estos elementos, por lo que ganamos mucha velocidad.

Además de esto, ciertas operaciones en NumPy, o librerías que requieren el uso de NumPy, necesitan que los operandos sean de un determinado tipo.

A continuación vamos a crear una serie de arrays de distintas dimensiones a partir de una lista propia de Python:

In [3]:
lista1D = [1, 5, 6, 79]
lista2D = [[2, 5.3, 0, -1.99], [14.5, 5, -5., 1]]
lista3D = [[[1, 5, 6, 79], [5, 7, 9, 0]], [[1, 5, 6, 79], [5, 7, 9, 0]]]

uni_dimensional = np.array(lista1D, dtype=np.int32) # Los elementos de este array serán enteros de 32 bits
bi_dimensional  = np.array(lista2D, dtype=np.float64) # En este caso, serán float de 64 bits
tri_dimensional = np.array(lista3D) # Y en este caso? 

print("Array 1D:\n", uni_dimensional)
print("Array 2D:\n", bi_dimensional)
print("Array 3D:\n", tri_dimensional)

Array 1D:
 [ 1  5  6 79]
Array 2D:
 [[  2.     5.3    0.    -1.99]
 [ 14.5    5.    -5.     1.  ]]
Array 3D:
 [[[ 1  5  6 79]
  [ 5  7  9  0]]

 [[ 1  5  6 79]
  [ 5  7  9  0]]]


Hay que tener encuenta que usar `np.array` requiere de un objeto ya existente, como en este caso son las listas utilizadas anteriormente. Este objeto es el que se inserta en el parámetro `object`. El otro parámetro más importante es `dtype` que nos sirve para indicar de qué tipo será el array que construyamos. Para más información sobre la creación de un array, puedes consultar la [documentación oficial](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html#numpy.array).

Además de crear arrays a partir de un objeto, NumPy nos ofrece la posibilidad de crear arrays "vacíos" o con valores predeterminados, gracias a las siguientes funciones:
* __`np.ones`__: genera un array de unos.
* __`np.zeros`__: genera un array de ceros.
* __`np.random.random`__: genera un array de números aleatorios.
* __`np.full`__: similar a `np.ones` con la diferencia de que todos los valores serán iguales al que reciba como parámetro.
* __`np.arange`__: genera un array con números dentro de un intervalo, con la frecuencia que queramos.
* __`np.linspace`__: similar al anterior, solo que fijamos el intervalo y el número de elementos que queremos.
* __`np.eye`__o __`np.identity`__: crean la matriz identidad.

##### Ejercicio
Ahora que hemos visto cómo crear arrays a partir de un objeto y otros para crear arrays con tipos prefijados, crea distintos arrays con las funciones anteriores para 1D, 2D y 3D e imprímelas por pantalla. Prueba a usar distintos tipos para ver cómo cambian los arrays. Si tienes dudas sobre cómo usarlos, puedes consultar la documentación oficial.

Una vez creado nuestros arrays, podemos encontrar información muy útil sobre ellos en los propios atributos del array. Estos atributos nos pueden dar información sobre el número de dimensiones, el espacio en memoria que ocupa cada elemento, etc. Los más comunes y el acceso a esta información podemos verlos a continuación:

In [4]:
x = np.arange(0.0,10.0,0.5)

print(x.ndim) # Nos muestra el número de dimensiones que tiene el array

print(x.size) # Muestra el número de elementos que tiene x

print(x.flags) # Nos muestra la información de los distintos flags de x

print(x.itemsize) # Nos muestra los bytes que ocupa un elemento de x

print(x.nbytes) # Nos muestra el número total de bytes que ocupan los elementos de x

1
20
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
8
160


Además de esto, podemos acceder a un elemento del array, podemos acceder de la misma manera que se hace en las listas de Python, usando el operador `[]`.

In [5]:
array_1d = np.arange(-5,5,1)
array_1d[1]

-4

También podemos acceder a subconjuntos dentro del array usando el operador `[]` y el operador `:` de la siguente forma:

In [6]:
array_1d[3:6]

array([-2, -1,  0])

Y usando estos dos mismos operadores, por ejemplo, en los arrays bidimensionales podemos acceder a todos los elementos de una fila o una columna de la siguiente forma:

In [7]:
array_random2d = np.random.random((4,6))
print("Matriz aleatoria:\n", array_random2d)

# Para acceder a todos los elementos de la segunda fila
print("Fila: \n", array_random2d[1])

# Para acceder a todos los elementos de la cuarta columna
print("Columna: \n", array_random2d[:,3])

# Filas de la segunda fila en adelante incluida esta
print("Filas: \n", array_random2d[1:])

# Columnas de la tercera columna en adelante
print("Columnas: \n", array_random2d[:,2:])

# Subconjuntos en filas y comunas
print("Subconjunto de columnas: \n", array_random2d[0:2,2:5])

Matriz aleatoria:
 [[  8.95516762e-01   7.89073905e-01   7.87589731e-01   7.32705212e-01
    3.46780526e-01   1.63848301e-04]
 [  3.46203514e-01   8.55052182e-01   7.50395947e-01   9.73898804e-01
    2.67168469e-01   6.31252351e-01]
 [  7.78338119e-01   6.98776690e-01   8.98304530e-01   5.23299243e-02
    6.77398321e-01   4.45937041e-01]
 [  9.23696447e-01   6.80856094e-01   4.88792944e-01   1.47153705e-01
    6.69500341e-01   1.16952698e-01]]
Fila: 
 [ 0.34620351  0.85505218  0.75039595  0.9738988   0.26716847  0.63125235]
Columna: 
 [ 0.73270521  0.9738988   0.05232992  0.14715371]
Filas: 
 [[ 0.34620351  0.85505218  0.75039595  0.9738988   0.26716847  0.63125235]
 [ 0.77833812  0.69877669  0.89830453  0.05232992  0.67739832  0.44593704]
 [ 0.92369645  0.68085609  0.48879294  0.14715371  0.66950034  0.1169527 ]]
Columnas: 
 [[  7.87589731e-01   7.32705212e-01   3.46780526e-01   1.63848301e-04]
 [  7.50395947e-01   9.73898804e-01   2.67168469e-01   6.31252351e-01]
 [  8.98304530e-01  

Ahora que ya sabemos cómo manejarnos con los arrays de NumPy, cómo crearlos y acceder a la información de ellos, ya podemos empezar a realizar operaciones matemáticas con ellos.

##### Ejercicio

Gracias a las distintas formas de indexar un array que nos permite NumPy, podemos hacer operaciones de forma vectorizada, evitando los bucles. Esto supone un incremento en la eficiencia del código y tener un código más corto y legible. Para ello, vamos a realizar el siguiente ejercicio. 

Genera una matriz aleatoria cuadrada de tamaño 1000. Una vez creada, genera una nueva matriz donde las filas y columnas 0 y $n-1$ estén repetidas 500 veces y el centro de la matriz quede exactamente igual a la original. Un ejemplo de esto lo podemos ver a continuación: $$\left(\begin{matrix} 1 & 2 & 2 & 2 & 3 \\ 2 & 3 & 3 & 3 & 4 \\ 2 & 3 & 3 & 3 & 4 \\ 2 & 3 & 3 & 3 & 4 \\ 3 & 4 & 4 & 4 & 5\end{matrix}\right) \Longrightarrow \left(\begin{matrix} 1 & 1 & 1 & 2 & 2 & 2 & 3 & 3 & 3 \\1 & 1 & 1 & 2 & 2 & 2 & 3 & 3 & 3 \\ 1 & 1 & 1 & 2 & 2 & 2 & 3 & 3 & 3 \\ 2 & 2 & 2 & 3 & 3 & 3 & 4 & 4 & 4 \\ 2 & 2 & 2 & 3 & 3 & 3 & 4 & 4 & 4 \\ 2 & 2 & 2 & 3 & 3 & 3 & 4 & 4 & 4 \\ 3 & 3 & 3 & 4 & 4 & 4 & 5 & 5 & 5 \\ 3 & 3 & 3 & 4 & 4 & 4 & 5 & 5 & 5 \\ 3 & 3 & 3 & 4 & 4 & 4 & 5 & 5 & 5\end{matrix}\right) $$ 

Impleméntalo usando un bucle `for` y vectorizando el cálculo usando lo anteriormente visto para ver la diferencias de tiempos usando ambas variantes. Para medir el tiempo, puedes usar el módulo `time`.

#### Operaciones con Arrays

Ahora que ya hemos visto cómo crear y manejar arrays, podemos pasar a ver cómo realizar operaciones aritméticas con ellos. NumPy tiene funciones como `np.add`, `np.substract`, `np.multiply` y `np.divide` para sumar, restar, multiplicar y dividir arrays. También podemos calcular el módulo entre dos arrays usando `np.remainder`. Pero, no es necesario usar estas funciones como tal, sino que podemos usar nuestros operadores aritméticos de siempre: `+`, `-`, `*`, `/` y `%`.

In [8]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Suma usando el operador +:\n\t", a + b)
print("Suma usando np.add:\n\t", np.add(a,b))

Suma usando el operador +:
	 [5 7 9]
Suma usando np.add:
	 [5 7 9]


También podemos encontrar funciones para calcular el coseno entre dos arrays, el producto vectorial, elevar a un exponente un array. Todas las funciones matemáticas las podemos encontrar en la [documentación](https://docs.scipy.org/doc/numpy/reference/routines.math.html).

Otro módulo muy importante de NumPy es el de álgebra lineal, que podemos acceder a las funciones de este módulo haciendo `np.linalg`. Este módulo contiene operaciones como el producto vectorial de dos arrays, la descomposición en valores singulares, funciones para resolver sistemas de ecuaciones, etc. Una vez más, la [documentación](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html) es nuestra amiga y en ella podemos encontrar toda la información sobre estas funciones, junto con ejemplos de uso.

##### Ejercicio

Una matriz de rotación $R$ es una matriz que representa una rotación en el espacio euclídeo. Esta matriz $R$ se representa como $$R=\left(\begin{matrix} \cos\theta & -\sin\theta \\ \sin\theta & -\cos\theta \end{matrix}\right)$$ donde $\theta$ es el número de ángulos rotados en sentido antihorario.

Estas matrices son muy usadas en geometría, informática o física. Un ejemplo de uso de estas matrices puede ser el cálculo de una rotación de un objeto en un sistema gráfico, la rotación de una cámara respecto a un punto en el espacio, etc.

Estas matrices tienen como propiedades que son ___matrices ortogonales___ (su inversa y su traspuesta son iguales) y su ___determinante es igual a 1___. Por tanto, genera un array y muestra si ese array es una matriz de rotación.

##### Ejercicio

Dados el array que se ve a continuación, realiza los siguientes apartados:

In [9]:
array1 = np.array([ -1., 4., -9.])

1. Multiplica `array1` por $\frac{\pi}{4}$ y calcula el seno del array resultante.
2. Genera un nuevo array cuyo valor sea el doble del resultado anterior mas el vector `array1`.
3. Calcula la norma del vector resultante. Para ello, consulta la documentación para ver qué función realiza esta tarea, y ten en cuenta los parámetros que recibe.

#### Operaciones lógicas

Además de las funciones algebraicas y aritméticas, también podemos hacer uso de los operadores lógicos para comparar dos arrays. Por ejemplo, si queremos comparar elemento a elemento si son iguales dos arrays, usaremos el operador `==`.

In [10]:
a = np.array([1, 2, 2, -1, 5])
b = np.array([0, 1, 2, 42, 5])

print(a == b)

[False False  True False  True]


Lo mismo sucede con los operadores de comparación `<` y `>`, que comparan elemento a elemento según el operador que hayamos decidido usar.

In [11]:
print("Operador <:\t", a < b)
print("Operador >:\t", a > b)
print("Operador <=:\t", a <= b)

Operador <:	 [False False False  True False]
Operador >:	 [ True  True False False False]
Operador <=:	 [False False  True  True  True]


Pero, en el caso de que queramos comparar si dos arrays son completamente iguales, devolviendo un único valor que sea `True` o `False`, debemos usar la función `np.array_equal(array_1, array_2)`.

In [12]:
print("¿Son iguales a y b?", np.array_equal(a, b))

¿Son iguales a y b? False


También están disponibles los operadores lógicos `&` y `|` para realizar operaciones lógicas con ellas. Sin embargo, NumPy también ofrece las funciones `np.logical_and()`, `np.logical_or()` para realizar estas operaciones y `np.logical_not` para negar el array.

Otras funciones a las que tenemos acceso son a funciones que nos ofrecen datos estadísticos como la _media_ o la _desviación típica_, o el valor de la suma de una fila de un array, etc. A continuación, podemos ver algunas de las que ofrece:
* __`array.sum()`__: devuelve la suma total de los componentes del array.
* __`array.min()`__: devuelve el mínimo valor del array.
* __`array.max()`__: devuelve el valor máximo de la fila o la columna, dependiendo del valor que tenga el parámetro `axis`.
* __`array.cumsum()`__: nos devuelve un nuevo array donde cada elemento es la suma acumulativa de los elementos del array. Al igual que antes, es dependiente del parámetro `axis`.
* __`array.mean()`__: para obtener la media.
* __`array.median()`__: para obtener la mediana.
* __`np.std(array)`__: para obtener la desviación típica del array.

##### Ejercicio

Dada la siguiente matriz, realiza los siguientes apartados:

In [13]:
n_array1 =  np.array([[ 1., 3., 5.], [7., -9., 2.], [4., 6., 8.]])

1. Calcula la media y la desviación típica de la matriz.
2. Obtén el elemento mínimo y máximo de la matriz.
3. Calcula el determinante, la traza y la traspuesta de la matriz.
4. Calcula la descomposición en valores singulares de la matriz.
5. Calcula el valor de la suma de los elementos de la diagonal principal de la matriz.

#### Salvar arrays de NumPy en ficheros

Hay veces que en nuestro problema podemos generar matrices de un tamaño considerable, y que el tiempo de cómputo que hemos necesitado para obtener esa matriz es demasiado grande como para permitirnos el lujo de generarlo de nuevo, o simplemente no es posible reproducir los cálculos.

Es por ello que NumPy ofrece una solución, y es que nos permite el poder salvar estos arrays en ficheros gracias a las funciones `save`, `savetxt`, `savez` o `savez_compressed`.
* __`save`__: guarda el array en un fichero binario de NumPy. Este fichero tiene como formato _.npy_.
* __`savetxt`__: guarda el array en un fichero de texto.
* __`savez`__: guarda varios arrays en un mismo fichero sin comprimir. Este fichero tiene formato _.npz_.
* __`savez_compressed`__: similar al anterior pero en este caso el fichero estará comprimido. Su formato también es _.npz_.

Para más infomración y ejemplos de uso, siempre podréis consultar la documentación oficial.

### Quiero más ejercicios para seguir entrenando con NumPy

Existe un repositorio en GitHub lleno de ejercicios que cubren un gran número de módulos y funciones de NumPy, con las soluciones a dichos ejercicios. Estos ejercicios, al igual que esta breve introducción, se encuentran en _jupyter-notebooks_ que podemos descargar y manipular. Este repositorio se encuentra [aquí](https://github.com/Kyubyong/numpy_exercises). Y recordar que siempre que useis un repositorio en GitHub y os ha sido de utilidad, dadle ___star___ al repositorio.

## Funciones _lambda_ ($\lambda$)