# Introducción a Python: nivel intermedio

Python es un lenguaje muy extendido, con una rica comunidad que abarca muchos aspectos, muy fácil de aprender y programar con él, y que nos permite realizar un montón de tareas diferentes. Pero, no solo de pan vive. Python tiene muchas _librerías_ o _módulos_ que nos facilitan muchas tareas, que están respaldados por un gran número de personas detrás y que en muchos casos, realizan tareas específicas de una manera mucho más eficiente que haciéndolo puramente en Python.

Este es el caso de librerías como ___NumPy___, ___Pandas___, ___scikit-learn___, ___Django___ y muchísimas más. 

Además de esto, aunque Python sea un lenguaje puramente imperativo, nos permite simular lo que se conoce como programación funcional, que viene directamente del _Lambda Calculus_, gracias al uso de las funciones ___lambda___.

A continuación, veremos una introducción a _NumPy_ que nos sirve como puerta de entrada a un montón de módulos más, y la programación funcional con las funciones _lambda_.

## NumPy

NumPy es el paquete central que usaremos para tareas como ciencia de datos, o muchos cálculos matemáticos que requieren el uso de estructuras algebraicas como los vectores y matrices. Este paquete tiene la ventaja de que podemos trabajar cómodamente con la sintaxis de Python, creando estructuras $n$-dimensionales de forma sencilla y realizar complejas funciones sobre estas estructuras en una sola línea de código muy eficiente. 

Esta eficiencia se debe a que NumPy utiliza código C para realizar estos cálculos, que es mucho más rápido que la misma implementación en Python.

Además de esto, otras de las grandes ventajas de NumPy es la documentación oficial que tiene, que es una de las más completas y bien documentadas que hay, ya que cubren muy bien todos los aspectos de las distintas funciones que tiene, además de incorporar una gran cantidad de ejemplos.

### Instalación

Para instalar NumPy tenemos que ejecutar la siguiente línea en nuestro terminal:
```
[braulio@braulio-PC ~]$ sudo pip install numpy
```
Con esto, gracias a pip, descargaremos e instalaremos NumPy. Así que, una vez instalados... a trabajar!!

### Primeros pasos con NumPy

Para empezar a trabajar con NumPy, lo primero es importar el paquete en nuestro script.

In [5]:
import numpy

Con esta línea, ya tendremos en nuestro pequeño script el paquete listo para ser usado. Para acceder a los módulos tendremos que hacer `numpy.nombre_de_la_función`. Esto no es que este mal, pero por así decirlo, el estandar es importar NumPy como se ve a continuación:

In [6]:
import numpy as np

De esta forma, vuestro código pasa a ser más legible, el resto de gente y mas cómodo y rápido de escribir. Además de que por convenio, debes importar NumPy como `np`.

### Arrays de NumPy

Numpy puede trabajar con arrays de $n$ dimensiones, pero los más comunes son los arrays de una, dos o tres dimensiones (1D, 2D, 3D). Además de esto, podemos establecer el tipo de los elementos del array a la hora de crearlo. Esto es muy importante, ya que si el array del tipo está determinado antes de ejecutar el script, Python no tiene que pararse a inferir el tipo de estos elementos, por lo que ganamos mucha velocidad.

Además de esto, ciertas operaciones en NumPy, o librerías que requieren el uso de NumPy, necesitan que los operandos sean de un determinado tipo.

A continuación vamos a crear una serie de arrays de distintas dimensiones a partir de una lista propia de Python:

In [7]:
lista1D = [1, 5, 6, 79]
lista2D = [[2, 5.3, 0, -1.99], [14.5, 5, -5., 1]]
lista3D = [[[1, 5, 6, 79], [5, 7, 9, 0]], [[1, 5, 6, 79], [5, 7, 9, 0]]]

uni_dimensional = np.array(lista1D, dtype=np.int32) # Los elementos de este array serán enteros de 32 bits
bi_dimensional  = np.array(lista2D, dtype=np.float64) # En este caso, serán float de 64 bits
tri_dimensional = np.array(lista3D) # Y en este caso? 

print("Array 1D:\n", uni_dimensional)
print("Array 2D:\n", bi_dimensional)
print("Array 3D:\n", tri_dimensional)

Array 1D:
 [ 1  5  6 79]
Array 2D:
 [[  2.     5.3    0.    -1.99]
 [ 14.5    5.    -5.     1.  ]]
Array 3D:
 [[[ 1  5  6 79]
  [ 5  7  9  0]]

 [[ 1  5  6 79]
  [ 5  7  9  0]]]


Hay que tener encuenta que usar `np.array` requiere de un objeto ya existente, como en este caso son las listas utilizadas anteriormente. Este objeto es el que se inserta en el parámetro `object`. El otro parámetro más importante es `dtype` que nos sirve para indicar de qué tipo será el array que construyamos. Para más información sobre la creación de un array, puedes consultar la [documentación oficial](https://docs.scipy.org/doc/numpy/reference/generated/numpy.array.html#numpy.array).

Además de crear arrays a partir de un objeto, NumPy nos ofrece la posibilidad de crear arrays "vacíos" o con valores predeterminados, gracias a las siguientes funciones:
* `np.ones`: genera un array de unos.
* `np.zeros`: genera un array de ceros.
* `np.random.random`: genera un array de números aleatorios.
* `np.full`: similar a `np.ones` con la diferencia de que todos los valores serán iguales al que reciba como parámetro.
* `np.arange`: genera un array con números dentro de un intervalo, con la frecuencia que queramos.
* `np.linspace`: similar al anterior, solo que fijamos el intervalo y el número de elementos que queremos.
* `np.eye`o `np.identity`: crean la matriz identidad.

#### Ejercicio
Ahora que hemos visto cómo crear arrays a partir de un objeto y otros para crear arrays con tipos prefijados, crea distintos arrays con las funciones anteriores para 1D, 2D y 3D e imprímelas por pantalla. Prueba a usar distintos tipos para ver cómo cambian los arrays. Si tienes dudas sobre cómo usarlos, puedes consultar la documentación oficial.

Una vez creado nuestros arrays, podemos encontrar información muy útil sobre ellos en los propios atributos del array. Estos atributos nos pueden dar información sobre el número de dimensiones, el espacio en memoria que ocupa cada elemento, etc. Los más comunes y el acceso a esta información podemos verlos a continuación:

In [8]:
x = np.arange(0.0,10.0,0.5)

print(x.ndim) # Nos muestra el número de dimensiones que tiene el array

print(x.size) # Muestra el número de elementos que tiene x

print(x.flags) # Nos muestra la información de los distintos flags de x

print(x.itemsize) # Nos muestra los bytes que ocupa un elemento de x

print(x.nbytes) # Nos muestra el número total de bytes que ocupan los elementos de x

1
20
  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False
8
160


Además de esto, podemos acceder a un elemento del array, podemos acceder de la misma manera que se hace en las listas de Python, usando el operador `[]`.

In [10]:
array_1d = np.arange(-5,5,1)
array_1d[1]

-4

También podemos acceder a subconjuntos dentro del array usando el operador `[]` y el operador `:` de la siguente forma:

In [11]:
array_1d[3:6]

array([-2, -1,  0])

Y usando estos dos mismos operadores, por ejemplo, en los arrays bidimensionales podemos acceder a todos los elementos de una fila o una columna de la siguiente forma:

In [28]:
array_random2d = np.random.random((4,6))
print("Matriz aleatoria:\n", array_random2d)

# Para acceder a todos los elementos de la segunda fila
print("Fila: \n", array_random2d[1])

# Para acceder a todos los elementos de la cuarta columna
print("Columna: \n", array_random2d[:,3])

# Filas de la segunda fila en adelante incluida esta
print("Filas: \n", array_random2d[1:])

# Columnas de la tercera columna en adelante
print("Columnas: \n", array_random2d[:,2:])

# Subconjuntos en filas y comunas
print("Subconjunto de columnas: \n", array_random2d[0:2,2:5])

Matriz aleatoria:
 [[ 0.62222884  0.491388    0.02480588  0.31600299  0.68396931  0.66550667]
 [ 0.31548418  0.9912079   0.24700319  0.57601663  0.31057263  0.75665549]
 [ 0.75351002  0.27424793  0.8668369   0.26174684  0.89091322  0.550716  ]
 [ 0.56395187  0.0246653   0.09668991  0.11680522  0.49145432  0.5637161 ]]
Fila: 
 [ 0.31548418  0.9912079   0.24700319  0.57601663  0.31057263  0.75665549]
Columna: 
 [ 0.31600299  0.57601663  0.26174684  0.11680522]
Filas: 
 [[ 0.31548418  0.9912079   0.24700319  0.57601663  0.31057263  0.75665549]
 [ 0.75351002  0.27424793  0.8668369   0.26174684  0.89091322  0.550716  ]
 [ 0.56395187  0.0246653   0.09668991  0.11680522  0.49145432  0.5637161 ]]
Columnas: 
 [[ 0.02480588  0.31600299  0.68396931  0.66550667]
 [ 0.24700319  0.57601663  0.31057263  0.75665549]
 [ 0.8668369   0.26174684  0.89091322  0.550716  ]
 [ 0.09668991  0.11680522  0.49145432  0.5637161 ]]
Subconjunto de columnas: 
 [[ 0.02480588  0.31600299  0.68396931]
 [ 0.24700319  0.57

Ahora que ya sabemos cómo manejarnos con los arrays de NumPy, cómo crearlos y acceder a la información de ellos, ya podemos empezar a realizar operaciones matemáticas con ellos.